version: "3"
services:  
  todo-api:
    build:
      dockerfile: Dockerfile
      context: ./todo-api
    ports:
      - "8080:8080"
  todo-frontend:
    stdin_open: true
    build:
      dockerfile: Dockerfile
      context: ./todo-frontend
    ports:
      - "80:3000"